name: "Cozi Proxy API"
version: "1.3.17"
slug: "cozi_proxy2"
description: "Local API bridge for Cozi To-Do lists"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true

# User-configurable options (shown in Supervisor UI)
options:
  username: ""
  password: ""

# Schema for the add-on configuration UI
schema:
  username: str
  password: str

# No need for environment variables anymore
environment: {}

ports:
  5000/tcp: 5000